### ISSUE TITLE
flaglist.csv is out of sync

### ISSUE THREAD

**Issue by arni-magnusson** [PacificCommunity/ofp-sam-flr4mfcl#20]
Based on the current MFCL manual, we should update flaglist.csv, changing:

Fish flag 23 "time step for q-devs [4.5.5]"
to
Fish flag 23 "time step for q-devs [4.5.6]"

Fish flag 24 "grouping for selectivity [4.5.6]"
to
Fish flag 24 "grouping for selectivity [4.5.7]"

Fish flag 16 "selectivity shape [4.5.6]"
to
Fish flag 16 "selectivity shape [4.5.7]"

Fish flag 75 "age classes for zero selectivity-at-age [4.5.6]"
to
Fish flag 75 "age classes for zero selectivity-at-age [4.5.7]"

**Comment by robscott3** [comment]
Apologies Arnie.

I have just amended flaglist.csv as suggested and pushed the changes - but noticed afterwards that you had assigned this task to yourself.
