### ISSUE TITLE
Cannot read in Par file with new MFCL version 2.0.8.4 

### ISSUE THREAD

**Issue by mtvincen** [PacificCommunity/ofp-sam-flr4mfcl#7]
The new version of MFCL 2.0.8.4 creates par files that are unable to be read in by FLR4MFCL. With this new version of MFCL it allows for an input of the tag shedding rate for the tag releases. This is done through the ini file by adding in vector of the tag shedding rates directly after the number of age classes and changing the version number to 1004. The length of the vector will be the length of the number of tag release events. 
There is now a par version 1065 that seems to correspond with the new ini and places the #tagmort vector after the #tag flags section.

This is the error that it gives when you attempt to read it in when you have that option active in MFCL
Error in data.frame(flagtype = rep(-1:-ntaggrps, each = 10) - 9999, flag = 1:10,  : 
  arguments imply differing number of rows: 120, 10, 112

Let me know if you would like help with reading this new par section in or have already been working on it.

**Comment by robscott3** [comment]
fixed - hopefully - added functionality to ini and par files for tag shedding (tagmort) and also made the y1_diff_coffs and y2_diff_coffs read/write code compatible with a single region model par file.
